# app.py

import os
from typing import List, Any
import streamlit as st
from agent_runner import (
    run_understanding_agent,
    run_mapping_agent,
    run_product_selector_agent,
    run_feedback_agent,
    run_final_output_agent
)


# STREAMLIT CONFIG & INTRO
# ------------------------------------------------------------------
st.set_page_config(
page_title="Excel Process Mapping",
layout="wide"
)

st.title("📊 Excel Process Mapping Assistant")

st.markdown(
"""
**Step 1.** Upload Excel files (your current process workbooks).

**Step 2.** Click **“🚀 Run analysis”** – the **Understanding Agent** analyses structure & relationships.

**Step 3.** The **Mapping Agent** and **Product Selector Agent** both use that JSON:
- Mapping Agent → generates a **process map PNG**
- Product Selector Agent → suggests **products / systems / tools**

**Step 4.** Use the **Feedback Agent** to tell the system what to improve in the map.

**Step 5.** The **Final Output Agent** combines everything into a **polished deliverable**.
"""
)

with st.sidebar:
    st.header("Workflow")
    st.markdown("1️⃣ Upload Excel files")
    st.markdown("2️⃣ Click **Run analysis**")
    st.markdown("3️⃣ Review JSON, process map PNG & product suggestions")
    st.markdown("4️⃣ Give feedback on the map")
    st.markdown("5️⃣ Download final output")


# HELPER: EXTRACT PNG BYTES FROM MAPPING AGENT OUTPUT
# ------------------------------------------------------------------
def _extract_png_bytes(map_result: Any) -> bytes | None:
    """
    map_result may be:
    - a file path (str) to the PNG
    - raw bytes or bytearray

    Returns PNG bytes or None.
    """
    if isinstance(map_result, str) and os.path.exists(map_result):
        with open(map_result, "rb") as f:
            return f.read()
    elif isinstance(map_result, (bytes, bytearray)):
        return bytes(map_result)
    return None

# STEP 1 – UPLOAD FILES
# ------------------------------------------------------------------
uploaded_files: List[Any] = st.file_uploader(
    "Upload 📂 Excel files",
    type=["xlsx", "xls", "xlsm"],
    accept_multiple_files=True,
)

if uploaded_files and len(uploaded_files) > 3:
    st.warning("You uploaded more than 3 files – only the first 3 will be used.")
    uploaded_files = uploaded_files[:3]

if uploaded_files:
    st.success(f"{len(uploaded_files)} file(s) ready:")
    for f in uploaded_files:
        st.write(f"- {f.name}")

# STEP 2 & 3 – RUN ANALYSIS BUTTON
# ------------------------------------------------------------------
run_button = st.button("🚀 Run analysis", type="primary")

if run_button:
    if not uploaded_files:
        st.error("Please upload at least one Excel file first.")
        st.stop()

# Step 2 – Understanding Agent
# ------------------------------
    with st.spinner("Running Understanding Agent (Gemini)…"):
        understanding_json = run_understanding_agent(uploaded_files)
        print("UNDERSTANDING JSON:", understanding_json)

    st.session_state["understanding_json"] = understanding_json

# Step 3 – Mapping + Product Agents
# ------------------------------

    # 3a – Mapping Agent (PNG)
    with st.spinner("Running Mapping Agent & generating PNG…"):
        map_result = run_mapping_agent(understanding_json)

    st.session_state["map_result"] = map_result

    # 3b – Product Selector Agent
    with st.spinner("Running Product Selector Agent…"):
        product_result = run_product_selector_agent(understanding_json)

    st.session_state["product_result"] = product_result

# DISPLAY STEP 2 OUTPUT – UNDERSTANDING AGENT
# ------------------------------------------------------------------
if "understanding_json" in st.session_state:
    st.markdown("---")
    st.subheader("Step 2 – 📄 Understanding Agent JSON output")

    understanding_json = st.session_state["understanding_json"]

    if isinstance(understanding_json, (dict, list)):
        st.json(understanding_json)
    else:
        st.write(understanding_json)

# DISPLAY STEP 3 OUTPUT – MAPPING & PRODUCT SELECTOR
# ------------------------------------------------------------------
if "map_result" in st.session_state or "product_result" in st.session_state:
    st.markdown("---")
    st.subheader("Step 3 – Mapping Agent & Product Selector Agent")

col_map, col_prod = st.columns(2)

# 3a – Mapping Agent output
with col_map:
    st.markdown("### 🗺️ Process Map (PNG)")

    if "map_result" in st.session_state:
        map_result = st.session_state["map_result"]
        png_bytes = _extract_png_bytes(map_result)

        if png_bytes:
            st.image(
                png_bytes,
                caption="Process map generated by Mapping Agent",
                use_column_width=True,
            )

            st.download_button(
                label="📥 Download process map PNG",
                data=png_bytes,
                file_name="process_map.png",
                mime="image/png",
            )
        else:
            st.error(f"Unexpected output from Mapping Agent: {type(map_result)}")
            st.write(map_result)
    else:
        st.info("Run the analysis to generate a process map.")

# 3b – Product Selector Agent output
with col_prod:
    st.markdown("### 🎯 Product recommendations")

    if "product_result" in st.session_state:
        product_result = st.session_state["product_result"]

        if isinstance(product_result, (dict, list)):
            st.json(product_result) 
        else:
            st.write(product_result)
    else:
        st.info("Run the analysis to generate product suggestions.")

# STEP 4 – FEEDBACK AGENT
# ------------------------------------------------------------------
if "understanding_json" in st.session_state and "map_result" in st.session_state:
    st.markdown("---")
    st.subheader("Step 4 – Feedback on the process map")

    st.markdown(
        "Use this section to tell the Feedback Agent what you like, what’s missing, "
        "or what should change in the process map."
    )

    feedback_text = st.text_area(
        "Your feedback on the process map",
        placeholder="e.g. 'The approvals step is missing', 'Combine steps 3 and 4', 'Rename the report to…'",
        key="feedback_text",
        height=150,
    )

    if st.button("✉️ Send feedback to Feedback Agent"):
        if not feedback_text.strip():
            st.warning("Please type some feedback before submitting.")
        else:
            with st.spinner("Running Feedback Agent…"):
                feedback_result = run_feedback_agent(
                    understanding_json=st.session_state["understanding_json"],
                    map_png_bytes=_extract_png_bytes(st.session_state["map_result"]),
                    user_feedback=feedback_text.strip(),
                )

            st.session_state["feedback_result"] = feedback_result
            st.success("Feedback Agent response")
            st.write(feedback_result)

# STEP 5 – FINAL OUTPUT AGENT
# ------------------------------------------------------------------
if (
    "understanding_json" in st.session_state
    and "map_result" in st.session_state
    and "product_result" in st.session_state
):
    st.markdown("---")
    st.subheader("Step 5 – Generate final deliverable")

    st.markdown(
        "This step combines the analysis, process map, product suggestions "
        "and (optionally) your feedback into a final polished output."
    )

    if st.button("📄 Generate final output"):
        with st.spinner("Running Final Output Agent…"):
            final_output = run_final_output_agent(
                understanding_json=st.session_state["understanding_json"],
                map_png_bytes=_extract_png_bytes(st.session_state["map_result"]),
                product_selection=st.session_state["product_result"],
                feedback=st.session_state.get("feedback_result"),
            )

        st.session_state["final_output"] = final_output
        st.success("Final output ready.")

# Show final output if it exists
    if "final_output" in st.session_state:
        final_output = st.session_state["final_output"]

        if isinstance(final_output, str):
            st.markdown("### Final deliverable (preview)")
            st.write(final_output)

            st.download_button(
                label="📥 Download final output (txt)",
                data=final_output.encode("utf-8"),
                file_name="final_output.txt",
                mime="text/plain",
                )
        else:
            st.write(final_output)